@version: 4.3
@include "scl.conf"

@module json-plugin

#   2025/11/18
#   works with fortigate kvp records (should also work with CEF)
#   sends to the stellar_Capture 5564 port on udp (can be changed to tcp if needed)
#   can probably be modified to work with any inbound records
#   and update the stellar_capture.conf to properly route the records based on the tag
#   the vendor, product, and log type fields are what are extracted in the initial parser and used to route
#   these are set below in the json builder


options {
    # DNS settings (optional, set to 'no' to improve performance)
    use-dns(no);
    dns-cache(no);
};


# 1. Define the Source
source s_fortigate {
    network(
        ip(0.0.0.0)
        transport("tcp")
        port(514)
        flags(no-parse) # We want to parse manually using the CEF parser
    );
};


# 2. Parse ONLY the VDOM using Regex
# This looks for "vd=" followed by any characters that are NOT a space
parser p_extract_vdom {
    regexp-parser(
        prefix(".reg.")        # Creates macro ${.reg.vdom_name}
        template("${MESSAGE}")
        #patterns("vd=(?<vdom_name>[^ ]+)")         # no quotes
        patterns("vd=[\"](?<vdom_name>[^ ]+)[\"]")  # quotes
    );
};

# 3. Enrich with Tenant ID (Lookup)
parser p_map_tenant {
    add-contextual-data(
        selector("${.reg.vdom_name}")     # Use the macro we extracted above
        database("/etc/syslog-ng/vdom_mapping.csv") # The CSV file
        prefix(".ctx.")                   # Prefix for the new variable
        default-selector("root")          # Optional: Fallback if VDOM not found
    );
};


# after contextual data is processed, there is a new soft macro
# prefix.valueinsecondcolumm
# if there is no match, the value is NULL


# 4. Define the JSON Destination
destination d_json_output {
    file("/var/log/fortigate_enriched.json"
        template("$(format-json
	    --pair stellar.tenantid=${.ctx.t-id}
	    --pair stellar.msg_origin.vendor=fortinet 
	    --pair stellar.msg_origin.product=fortigate
	    --pair stellar.msg_origin.format=syslog
	    --pair stellar.msg_origin.srcip=${HOST}
            --pair parser_raw_msg='${MESSAGE}'
       )\n")
    );
};
            #--pair raw_message=${MESSAGE} # The original message payload
	        # --pair preselector=${.ctx.*}
            # --pair tenantid=${.ctx.t-id}     # '.ctx.' is the prefix, '1' is the column index from CSV
	        # --pair vdom_name=${.reg.vdom_name}
            # --scope selected_macros       # Optional: Include other parsed fields if desired

# network shipper
destination d_udp_target {
    network(
	"192.168.1.22"
	port(5564)
	transport("udp")
        template("$(format-json
            --pair stellar.tenantid=${.ctx.t-id}
            --pair stellar.msg_origin.vendor=fortinet
            --pair stellar.msg_origin.product=fortigate
            --pair stellar.msg_origin.format=syslog
            --pair stellar.msg_origin.srcip=${HOST}
            --pair parser_raw_msg=${MESSAGE}
       )\n")
    );
};

# 5. Connect the Log Path
log {
    source(s_fortigate);
    parser(p_extract_vdom);
    parser(p_map_tenant);
    # destination(d_json_output);
    destination(d_udp_target);
};