@version: 4.3
@include "scl.conf"

@module json-plugin

#   2026/03/24
#   works with the palo_alto_networks parser
#   sends to the stellar_Capture 5564 port on udp (can be changed to tcp if needed)
#   can probably be modified to work with any inbound records
#   and update the stellar_capture.conf to properly route the records based on the tag
#   the vendor, product, and log type fields are what are extracted in the initial parser and used to route
#   these are set below in the json builder


options {
    # DNS settings (optional, set to 'no' to improve performance)
    use-dns(no);
    dns-cache(no);
};


# 1. Define the Source
source s_palo_alto {
    network(
        ip(0.0.0.0)
        transport("tcp")
        port(514)
        flags(no-parse) # We want to parse manually in the log forwarder
    );
};


# 2. Parse the serial number
# This looks for the SN following the hostname
# the SN in this example is 021209012681
# <134>2026-03-24T17:31:20+00:00 A2A-PA440 1,2026/03/24 17:31:15,021209012681,TRAFFIC

parser p_extract_sn {
    regexp-parser(
        prefix(".reg.")        # Creates macro ${.reg.dev_sn}
        template("${MESSAGE}")
        patterns(".*\:[0-9]{2}\,(?<dev_sn>[0-9]{12})\,[a-zA-Z]+\,.*")
    );
};

# 3. Enrich with Tenant ID (Lookup)
parser p_map_tenant {
    add-contextual-data(
        selector("${.reg.dev_sn}")                  # Use the macro we extracted above
        database("/etc/syslog-ng/sn_mapping.csv")   # The CSV file
        prefix(".ctx.")                   # Prefix for the new variable
        default-selector("root")          # Optional: Fallback if SN not found
    );
};

# after contextual data is processed, there is a new soft macro
# prefix.valueinsecondcolumm
# if there is no match, the value is NULL

# 4. Define the JSON Destination
destination d_json_output {
    file("/var/log/pan_enriched.json"
        template("$(format-json
        --pair stellar.tenantid=${.ctx.t-id}
        --pair stellar.msg_origin.vendor=palo_alto_networks
        --pair stellar.msg_origin.product=firewall
        --pair stellar.msg_origin.format=syslog
        --pair stellar.msg_origin.srcip=${HOST}
        --pair parser_raw_msg='${MESSAGE}'
       )\n")
    );
};

# network shipper
destination d_udp_target {
    network(
    "192.168.1.22"
    port(5564)
    transport("udp")
        template("$(format-json
            --pair stellar.tenantid=${.ctx.t-id}
            --pair stellar.msg_origin.vendor=palo_alto_networks
            --pair stellar.msg_origin.product=firewall
            --pair stellar.msg_origin.format=syslog
            --pair stellar.msg_origin.srcip=${HOST}
            --pair parser_raw_msg=${MESSAGE}
       )\n")
    );
};

# 5. Connect the Log Path
log {
    source(s_palo_alto);
    parser(p_extract_sn);
    parser(p_map_tenant);
    #destination(d_json_output);
    destination(d_udp_target);
};